- hosts: all
  gather_facts: false
  pre_tasks:
    - when: inventory_hostname == 'localhost'
      set_fact:
        ansible_connection: local
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars:
    homebrew_taps:
      - homebrew/cask
      - d12frosted/emacs-plus # for emacs-plus

    homebrew_cask_packages:
      - name: appcleaner
      - name: slack
      - name: telegram
      - name: vagrant
      - name: virtualbox
      - name: zoomus

    homebrew_packages:
      - name: autogen
      - name: bash
      - name: cmake
      - name: coreutils
      - name: curl
      - name: emacs-plus
      - name: fzf
      - name: go
      - name: gpg
      - name: htop
      - name: hub
      - name: jq
      - name: mosh
      - name: pinentry-mac
      - name: procs
      - name: pyenv
      - name: python
      - name: python3
      - name: rsync
      - name: rustup-init
      - name: screen
      - name: stow
      - name: tree
      - name: wget

  tasks:
    - name: homebrew updatep
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew:
        name: '{{ item.name }}'
        state: present
      environment:
        HOMEBREW_CASK_OPTS: "--cask --appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
